export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan`,
    require('./scheduleManagementPlanCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan/:id`,
    require('./scheduleManagementPlanUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan/import`,
    require('./scheduleManagementPlanImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan`,
    require('./scheduleManagementPlanDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan/autocomplete`,
    require('./scheduleManagementPlanAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan`,
    require('./scheduleManagementPlanList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/schedule-management-plan/:id`,
    require('./scheduleManagementPlanFind').default,
  );
};
