export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/requirement-documentation`,
    require('./requirementDocumentationCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/requirement-documentation/:id`,
    require('./requirementDocumentationUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/requirement-documentation/import`,
    require('./requirementDocumentationImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/requirement-documentation`,
    require('./requirementDocumentationDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/requirement-documentation/autocomplete`,
    require('./requirementDocumentationAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/requirement-documentation`,
    require('./requirementDocumentationList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/requirement-documentation/:id`,
    require('./requirementDocumentationFind').default,
  );
};
