export default (app) => {
  app.post(
    `/tenant/:tenantId/stakeholder-registration`,
    require('./stakeholderRegistrationCreate').default,
  );
  app.put(
    `/tenant/:tenantId/stakeholder-registration/:id`,
    require('./stakeholderRegistrationUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/stakeholder-registration/import`,
    require('./stakeholderRegistrationImport').default,
  );
  app.delete(
    `/tenant/:tenantId/stakeholder-registration`,
    require('./stakeholderRegistrationDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/stakeholder-registration/autocomplete`,
    require('./stakeholderRegistrationAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/stakeholder-registration`,
    require('./stakeholderRegistrationList').default,
  );
  app.get(
    `/tenant/:tenantId/stakeholder-registration/:id`,
    require('./stakeholderRegistrationFind').default,
  );
};
