export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/activity-list`,
    require('./activityListCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/activity-list/:id`,
    require('./activityListUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/activity-list/import`,
    require('./activityListImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/activity-list`,
    require('./activityListDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/activity-list/autocomplete`,
    require('./activityListAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/activity-list`,
    require('./activityListList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/activity-list/:id`,
    require('./activityListFind').default,
  );
};
