export default (app) => {
  app.post(
    `/tenant/:tenantId/project-closure`,
    require('./projectClosureCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project-closure/:id`,
    require('./projectClosureUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project-closure/import`,
    require('./projectClosureImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project-closure`,
    require('./projectClosureDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project-closure/autocomplete`,
    require('./projectClosureAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project-closure`,
    require('./projectClosureList').default,
  );
  app.get(
    `/tenant/:tenantId/project-closure/:id`,
    require('./projectClosureFind').default,
  );
};
