export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/cost-estimates`,
    require('./costEstimatesCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/cost-estimates/:id`,
    require('./costEstimatesUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/cost-estimates/import`,
    require('./costEstimatesImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/cost-estimates`,
    require('./costEstimatesDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/cost-estimates/autocomplete`,
    require('./costEstimatesAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/cost-estimates`,
    require('./costEstimatesList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/cost-estimates/:id`,
    require('./costEstimatesFind').default,
  );
};
