export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars`,
    require('./stakeholderCalendarsCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars/:id`,
    require('./stakeholderCalendarsUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars/import`,
    require('./stakeholderCalendarsImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars`,
    require('./stakeholderCalendarsDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars/autocomplete`,
    require('./stakeholderCalendarsAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars`,
    require('./stakeholderCalendarsList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/stakeholder-calendars/:id`,
    require('./stakeholderCalendarsFind').default,
  );
};
