export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates`,
    require('./activityDurationEstimatesCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates/:id`,
    require('./activityDurationEstimatesUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates/import`,
    require('./activityDurationEstimatesImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates`,
    require('./activityDurationEstimatesDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates/autocomplete`,
    require('./activityDurationEstimatesAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates`,
    require('./activityDurationEstimatesList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/activity-duration-estimates/:id`,
    require('./activityDurationEstimatesFind').default,
  );
};
