export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/scope-management-plan`,
    require('./scopeManagementPlanCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/scope-management-plan/:id`,
    require('./scopeManagementPlanUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/scope-management-plan/import`,
    require('./scopeManagementPlanImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/scope-management-plan`,
    require('./scopeManagementPlanDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/scope-management-plan/autocomplete`,
    require('./scopeManagementPlanAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/scope-management-plan`,
    require('./scopeManagementPlanList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/scope-management-plan/:id`,
    require('./scopeManagementPlanFind').default,
  );
};
