export default (app) => {
  app.post(
    `/tenant/:tenantId/communications-management-plan`,
    require('./communicationsManagementPlanCreate').default,
  );
  app.put(
    `/tenant/:tenantId/communications-management-plan/:id`,
    require('./communicationsManagementPlanUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/communications-management-plan/import`,
    require('./communicationsManagementPlanImport').default,
  );
  app.delete(
    `/tenant/:tenantId/communications-management-plan`,
    require('./communicationsManagementPlanDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/communications-management-plan/autocomplete`,
    require('./communicationsManagementPlanAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/communications-management-plan`,
    require('./communicationsManagementPlanList').default,
  );
  app.get(
    `/tenant/:tenantId/communications-management-plan/:id`,
    require('./communicationsManagementPlanFind').default,
  );
};
