export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/resource-requirements`,
    require('./resourceRequirementsCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/resource-requirements/:id`,
    require('./resourceRequirementsUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/resource-requirements/import`,
    require('./resourceRequirementsImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/resource-requirements`,
    require('./resourceRequirementsDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/resource-requirements/autocomplete`,
    require('./resourceRequirementsAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/resource-requirements`,
    require('./resourceRequirementsList').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/resource-requirements/:id`,
    require('./resourceRequirementsFind').default,
  );
};
