export default (app) => {
  app.post(
    `/tenant/:tenantId/project/:projectId/business-case`,
    require('./businessCaseCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project/:projectId/business-case/:id`,
    require('./businessCaseUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project/:projectId/business-case/import`,
    require('./businessCaseImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project/:projectId/business-case`,
    require('./businessCaseDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/business-case/autocomplete`,
    require('./businessCaseAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project/:projectId/business-case`,
    require('./businessCaseList').default,
  );
  app.get(
    `/tenant/:tenantId/business-case/:id`,
    require('./businessCaseFind').default,
  );
};
