export default (app) => {
  app.post(
    `/tenant/:tenantId/risk-registration`,
    require('./riskRegistrationCreate').default,
  );
  app.put(
    `/tenant/:tenantId/risk-registration/:id`,
    require('./riskRegistrationUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/risk-registration/import`,
    require('./riskRegistrationImport').default,
  );
  app.delete(
    `/tenant/:tenantId/risk-registration`,
    require('./riskRegistrationDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/risk-registration/autocomplete`,
    require('./riskRegistrationAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/risk-registration`,
    require('./riskRegistrationList').default,
  );
  app.get(
    `/tenant/:tenantId/risk-registration/:id`,
    require('./riskRegistrationFind').default,
  );
};
