export default (app) => {
  app.post(
    `/tenant/:tenantId/project-performance-monitoring-report`,
    require('./projectPerformanceMonitoringReportCreate').default,
  );
  app.put(
    `/tenant/:tenantId/project-performance-monitoring-report/:id`,
    require('./projectPerformanceMonitoringReportUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/project-performance-monitoring-report/import`,
    require('./projectPerformanceMonitoringReportImport').default,
  );
  app.delete(
    `/tenant/:tenantId/project-performance-monitoring-report`,
    require('./projectPerformanceMonitoringReportDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/project-performance-monitoring-report/autocomplete`,
    require('./projectPerformanceMonitoringReportAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/project-performance-monitoring-report`,
    require('./projectPerformanceMonitoringReportList').default,
  );
  app.get(
    `/tenant/:tenantId/project-performance-monitoring-report/:id`,
    require('./projectPerformanceMonitoringReportFind').default,
  );
};
